<?xml version="1.0" encoding="utf-8"?><Database Name="TrabajoFinal" Class="BaseDatosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-VLDD9KS;Initial Catalog=TrabajoFinal;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TrabajoFinalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vendedor" Member="Vendedors">
    <Type Name="Vendedor">
      <Column Name="IdVendedor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Administrador" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Contrasenia" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="Vendedor_Pedido" Member="Pedidos" ThisKey="IdVendedor" OtherKey="IdVendedor" Type="Pedido" />
    </Type>
  </Table>
  <Table Name="dbo.Articulo" Member="Articulos">
    <Type Name="Articulo">
      <Column Name="IdArticulo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Denominacion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioCompra" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PrecioVenta" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IdRubro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Articulo_Detalle" Member="Detalles" ThisKey="IdArticulo" OtherKey="IdArticulo" Type="Detalle" />
      <Association Name="Rubro_Articulo" Member="Rubro" ThisKey="IdRubro" OtherKey="IdRubro" Type="Rubro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RazonSocial" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cuit" Type="System.String" DbType="NVarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="Saldo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IdDomicilio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Cliente_Pedido" Member="Pedidos" ThisKey="IdCliente" OtherKey="IdCliente" Type="Pedido" />
      <Association Name="Domicilio_Cliente" Member="Domicilio" ThisKey="IdDomicilio" OtherKey="IdDomicilio" Type="Domicilio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Detalle" Member="Detalles">
    <Type Name="Detalle">
      <Column Name="IdDetalle" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Descuento" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IdPedido" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdArticulo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Articulo_Detalle" Member="Articulo" ThisKey="IdArticulo" OtherKey="IdArticulo" Type="Articulo" IsForeignKey="true" />
      <Association Name="Pedido_Detalle" Member="Pedido" ThisKey="IdPedido" OtherKey="IdPedido" Type="Pedido" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Domicilio" Member="Domicilios">
    <Type Name="Domicilio">
      <Column Name="IdDomicilio" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Calle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Latitud" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Longitud" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IdLocalidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Domicilio_Cliente" Member="Clientes" ThisKey="IdDomicilio" OtherKey="IdDomicilio" Type="Cliente" />
      <Association Name="Localidad_Domicilio" Member="Localidad" ThisKey="IdLocalidad" OtherKey="IdLocalidad" Type="Localidad" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Localidad" Member="Localidads">
    <Type Name="Localidad">
      <Column Name="IdLocalidad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Denominacion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdProvincia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Localidad_Domicilio" Member="Domicilios" ThisKey="IdLocalidad" OtherKey="IdLocalidad" Type="Domicilio" />
      <Association Name="Provincia_Localidad" Member="Provincia" ThisKey="IdProvincia" OtherKey="IdProvincia" Type="Provincia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pais" Member="Pais">
    <Type Name="Pai">
      <Column Name="IdPais" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Denominacion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Pai_Provincia" Member="Provincias" ThisKey="IdPais" OtherKey="IdPais" Type="Provincia" />
    </Type>
  </Table>
  <Table Name="dbo.Pedido" Member="Pedidos">
    <Type Name="Pedido">
      <Column Name="IdPedido" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Editable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Pagado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FechaPedido" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="FechaEntrega" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="SubTotal" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="GastosEnvio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdVendedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Pedido_Detalle" Member="Detalles" ThisKey="IdPedido" OtherKey="IdPedido" Type="Detalle" />
      <Association Name="Cliente_Pedido" Member="Cliente" ThisKey="IdCliente" OtherKey="IdCliente" Type="Cliente" IsForeignKey="true" />
      <Association Name="Vendedor_Pedido" Member="Vendedor" ThisKey="IdVendedor" OtherKey="IdVendedor" Type="Vendedor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Provincia" Member="Provincias">
    <Type Name="Provincia">
      <Column Name="IdProvincia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Denominacion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdPais" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Provincia_Localidad" Member="Localidads" ThisKey="IdProvincia" OtherKey="IdProvincia" Type="Localidad" />
      <Association Name="Pai_Provincia" Member="Pai" ThisKey="IdPais" OtherKey="IdPais" Type="Pai" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rubro" Member="Rubros">
    <Type Name="Rubro">
      <Column Name="IdRubro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Denominacion" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IdRubroSuperior" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Rubro_Articulo" Member="Articulos" ThisKey="IdRubro" OtherKey="IdRubro" Type="Articulo" />
      <Association Name="Rubro_Rubro" Member="Rubros" ThisKey="IdRubro" OtherKey="IdRubroSuperior" Type="Rubro" />
      <Association Name="Rubro_Rubro" Member="Rubro1" ThisKey="IdRubroSuperior" OtherKey="IdRubro" Type="Rubro" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetIdentityRubro" Method="GetIdentityRubro">
    <ElementType Name="GetIdentityRubroResult">
      <Column Name="" Member="Column1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetIdentityArticulo" Method="GetIdentityArticulo">
    <ElementType Name="GetIdentityArticuloResult">
      <Column Name="" Member="Column1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetIdentityPedido" Method="GetIdentityPedido">
    <ElementType Name="GetIdentityPedidoResult">
      <Column Name="" Member="Column1" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>