#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TrabajoFinal")]
public partial class BaseDatosDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertArticulo(Articulo instance);
  partial void UpdateArticulo(Articulo instance);
  partial void DeleteArticulo(Articulo instance);
  partial void InsertVendedor(Vendedor instance);
  partial void UpdateVendedor(Vendedor instance);
  partial void DeleteVendedor(Vendedor instance);
  partial void InsertCliente(Cliente instance);
  partial void UpdateCliente(Cliente instance);
  partial void DeleteCliente(Cliente instance);
  partial void InsertDomicilio(Domicilio instance);
  partial void UpdateDomicilio(Domicilio instance);
  partial void DeleteDomicilio(Domicilio instance);
  partial void InsertPedidoVenta(PedidoVenta instance);
  partial void UpdatePedidoVenta(PedidoVenta instance);
  partial void DeletePedidoVenta(PedidoVenta instance);
  partial void InsertPedidoVentaDetalle(PedidoVentaDetalle instance);
  partial void UpdatePedidoVentaDetalle(PedidoVentaDetalle instance);
  partial void DeletePedidoVentaDetalle(PedidoVentaDetalle instance);
  partial void InsertRubro(Rubro instance);
  partial void UpdateRubro(Rubro instance);
  partial void DeleteRubro(Rubro instance);
  #endregion
	
	public BaseDatosDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TrabajoFinalConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public BaseDatosDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BaseDatosDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BaseDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public BaseDatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Articulo> Articulos
	{
		get
		{
			return this.GetTable<Articulo>();
		}
	}
	
	public System.Data.Linq.Table<Vendedor> Vendedors
	{
		get
		{
			return this.GetTable<Vendedor>();
		}
	}
	
	public System.Data.Linq.Table<Cliente> Clientes
	{
		get
		{
			return this.GetTable<Cliente>();
		}
	}
	
	public System.Data.Linq.Table<Domicilio> Domicilios
	{
		get
		{
			return this.GetTable<Domicilio>();
		}
	}
	
	public System.Data.Linq.Table<PedidoVenta> PedidoVentas
	{
		get
		{
			return this.GetTable<PedidoVenta>();
		}
	}
	
	public System.Data.Linq.Table<PedidoVentaDetalle> PedidoVentaDetalles
	{
		get
		{
			return this.GetTable<PedidoVentaDetalle>();
		}
	}
	
	public System.Data.Linq.Table<Rubro> Rubros
	{
		get
		{
			return this.GetTable<Rubro>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Articulo")]
public partial class Articulo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IdArticulo;
	
	private string _Denominacion;
	
	private string _Codigo;
	
	private System.Nullable<double> _PrecioCompra;
	
	private System.Nullable<double> _PrecioVenta;
	
	private System.Nullable<double> _Iva;
	
	private System.Nullable<int> _IdRubro;
	
	private EntitySet<PedidoVentaDetalle> _PedidoVentaDetalles;
	
	private EntityRef<Rubro> _Rubro;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdArticuloChanging(int value);
    partial void OnIdArticuloChanged();
    partial void OnDenominacionChanging(string value);
    partial void OnDenominacionChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnPrecioCompraChanging(System.Nullable<double> value);
    partial void OnPrecioCompraChanged();
    partial void OnPrecioVentaChanging(System.Nullable<double> value);
    partial void OnPrecioVentaChanged();
    partial void OnIvaChanging(System.Nullable<double> value);
    partial void OnIvaChanged();
    partial void OnIdRubroChanging(System.Nullable<int> value);
    partial void OnIdRubroChanged();
    #endregion
	
	public Articulo()
	{
		this._PedidoVentaDetalles = new EntitySet<PedidoVentaDetalle>(new Action<PedidoVentaDetalle>(this.attach_PedidoVentaDetalles), new Action<PedidoVentaDetalle>(this.detach_PedidoVentaDetalles));
		this._Rubro = default(EntityRef<Rubro>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArticulo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IdArticulo
	{
		get
		{
			return this._IdArticulo;
		}
		set
		{
			if ((this._IdArticulo != value))
			{
				this.OnIdArticuloChanging(value);
				this.SendPropertyChanging();
				this._IdArticulo = value;
				this.SendPropertyChanged("IdArticulo");
				this.OnIdArticuloChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denominacion", DbType="VarChar(200)")]
	public string Denominacion
	{
		get
		{
			return this._Denominacion;
		}
		set
		{
			if ((this._Denominacion != value))
			{
				this.OnDenominacionChanging(value);
				this.SendPropertyChanging();
				this._Denominacion = value;
				this.SendPropertyChanged("Denominacion");
				this.OnDenominacionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20)")]
	public string Codigo
	{
		get
		{
			return this._Codigo;
		}
		set
		{
			if ((this._Codigo != value))
			{
				this.OnCodigoChanging(value);
				this.SendPropertyChanging();
				this._Codigo = value;
				this.SendPropertyChanged("Codigo");
				this.OnCodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioCompra", DbType="Float")]
	public System.Nullable<double> PrecioCompra
	{
		get
		{
			return this._PrecioCompra;
		}
		set
		{
			if ((this._PrecioCompra != value))
			{
				this.OnPrecioCompraChanging(value);
				this.SendPropertyChanging();
				this._PrecioCompra = value;
				this.SendPropertyChanged("PrecioCompra");
				this.OnPrecioCompraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVenta", DbType="Float")]
	public System.Nullable<double> PrecioVenta
	{
		get
		{
			return this._PrecioVenta;
		}
		set
		{
			if ((this._PrecioVenta != value))
			{
				this.OnPrecioVentaChanging(value);
				this.SendPropertyChanging();
				this._PrecioVenta = value;
				this.SendPropertyChanged("PrecioVenta");
				this.OnPrecioVentaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iva", DbType="Float")]
	public System.Nullable<double> Iva
	{
		get
		{
			return this._Iva;
		}
		set
		{
			if ((this._Iva != value))
			{
				this.OnIvaChanging(value);
				this.SendPropertyChanging();
				this._Iva = value;
				this.SendPropertyChanged("Iva");
				this.OnIvaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRubro", DbType="Int")]
	public System.Nullable<int> IdRubro
	{
		get
		{
			return this._IdRubro;
		}
		set
		{
			if ((this._IdRubro != value))
			{
				if (this._Rubro.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdRubroChanging(value);
				this.SendPropertyChanging();
				this._IdRubro = value;
				this.SendPropertyChanged("IdRubro");
				this.OnIdRubroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Articulo_PedidoVentaDetalle", Storage="_PedidoVentaDetalles", ThisKey="IdArticulo", OtherKey="IdArticulo")]
	public EntitySet<PedidoVentaDetalle> PedidoVentaDetalles
	{
		get
		{
			return this._PedidoVentaDetalles;
		}
		set
		{
			this._PedidoVentaDetalles.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rubro_Articulo", Storage="_Rubro", ThisKey="IdRubro", OtherKey="IdRubro", IsForeignKey=true)]
	public Rubro Rubro
	{
		get
		{
			return this._Rubro.Entity;
		}
		set
		{
			Rubro previousValue = this._Rubro.Entity;
			if (((previousValue != value) 
						|| (this._Rubro.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Rubro.Entity = null;
					previousValue.Articulos.Remove(this);
				}
				this._Rubro.Entity = value;
				if ((value != null))
				{
					value.Articulos.Add(this);
					this._IdRubro = value.IdRubro;
				}
				else
				{
					this._IdRubro = default(Nullable<int>);
				}
				this.SendPropertyChanged("Rubro");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_PedidoVentaDetalles(PedidoVentaDetalle entity)
	{
		this.SendPropertyChanging();
		entity.Articulo = this;
	}
	
	private void detach_PedidoVentaDetalles(PedidoVentaDetalle entity)
	{
		this.SendPropertyChanging();
		entity.Articulo = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vendedor")]
public partial class Vendedor : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IdVendedor;
	
	private string _Usuario;
	
	private string _Contrasenia;
	
	private string _Nombre;
	
	private string _Apellido;
	
	private EntitySet<PedidoVenta> _PedidoVentas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVendedorChanging(int value);
    partial void OnIdVendedorChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContraseniaChanging(string value);
    partial void OnContraseniaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidoChanging(string value);
    partial void OnApellidoChanged();
    #endregion
	
	public Vendedor()
	{
		this._PedidoVentas = new EntitySet<PedidoVenta>(new Action<PedidoVenta>(this.attach_PedidoVentas), new Action<PedidoVenta>(this.detach_PedidoVentas));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVendedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IdVendedor
	{
		get
		{
			return this._IdVendedor;
		}
		set
		{
			if ((this._IdVendedor != value))
			{
				this.OnIdVendedorChanging(value);
				this.SendPropertyChanging();
				this._IdVendedor = value;
				this.SendPropertyChanged("IdVendedor");
				this.OnIdVendedorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(12)")]
	public string Usuario
	{
		get
		{
			return this._Usuario;
		}
		set
		{
			if ((this._Usuario != value))
			{
				this.OnUsuarioChanging(value);
				this.SendPropertyChanging();
				this._Usuario = value;
				this.SendPropertyChanged("Usuario");
				this.OnUsuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasenia", DbType="VarChar(12)")]
	public string Contrasenia
	{
		get
		{
			return this._Contrasenia;
		}
		set
		{
			if ((this._Contrasenia != value))
			{
				this.OnContraseniaChanging(value);
				this.SendPropertyChanging();
				this._Contrasenia = value;
				this.SendPropertyChanged("Contrasenia");
				this.OnContraseniaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this.OnNombreChanging(value);
				this.SendPropertyChanging();
				this._Nombre = value;
				this.SendPropertyChanged("Nombre");
				this.OnNombreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(50)")]
	public string Apellido
	{
		get
		{
			return this._Apellido;
		}
		set
		{
			if ((this._Apellido != value))
			{
				this.OnApellidoChanging(value);
				this.SendPropertyChanging();
				this._Apellido = value;
				this.SendPropertyChanged("Apellido");
				this.OnApellidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendedor_PedidoVenta", Storage="_PedidoVentas", ThisKey="IdVendedor", OtherKey="IdVendedor")]
	public EntitySet<PedidoVenta> PedidoVentas
	{
		get
		{
			return this._PedidoVentas;
		}
		set
		{
			this._PedidoVentas.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_PedidoVentas(PedidoVenta entity)
	{
		this.SendPropertyChanging();
		entity.Vendedor = this;
	}
	
	private void detach_PedidoVentas(PedidoVenta entity)
	{
		this.SendPropertyChanging();
		entity.Vendedor = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IdCliente;
	
	private string _RazonSocial;
	
	private string _Cuit;
	
	private System.Nullable<double> _Saldo;
	
	private System.Nullable<int> _IdDomicilio;
	
	private EntitySet<PedidoVenta> _PedidoVentas;
	
	private EntityRef<Domicilio> _Domicilio;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnRazonSocialChanging(string value);
    partial void OnRazonSocialChanged();
    partial void OnCuitChanging(string value);
    partial void OnCuitChanged();
    partial void OnSaldoChanging(System.Nullable<double> value);
    partial void OnSaldoChanged();
    partial void OnIdDomicilioChanging(System.Nullable<int> value);
    partial void OnIdDomicilioChanged();
    #endregion
	
	public Cliente()
	{
		this._PedidoVentas = new EntitySet<PedidoVenta>(new Action<PedidoVenta>(this.attach_PedidoVentas), new Action<PedidoVenta>(this.detach_PedidoVentas));
		this._Domicilio = default(EntityRef<Domicilio>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IdCliente
	{
		get
		{
			return this._IdCliente;
		}
		set
		{
			if ((this._IdCliente != value))
			{
				this.OnIdClienteChanging(value);
				this.SendPropertyChanging();
				this._IdCliente = value;
				this.SendPropertyChanged("IdCliente");
				this.OnIdClienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocial", DbType="VarChar(100)")]
	public string RazonSocial
	{
		get
		{
			return this._RazonSocial;
		}
		set
		{
			if ((this._RazonSocial != value))
			{
				this.OnRazonSocialChanging(value);
				this.SendPropertyChanging();
				this._RazonSocial = value;
				this.SendPropertyChanged("RazonSocial");
				this.OnRazonSocialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuit", DbType="VarChar(20)")]
	public string Cuit
	{
		get
		{
			return this._Cuit;
		}
		set
		{
			if ((this._Cuit != value))
			{
				this.OnCuitChanging(value);
				this.SendPropertyChanging();
				this._Cuit = value;
				this.SendPropertyChanged("Cuit");
				this.OnCuitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Float")]
	public System.Nullable<double> Saldo
	{
		get
		{
			return this._Saldo;
		}
		set
		{
			if ((this._Saldo != value))
			{
				this.OnSaldoChanging(value);
				this.SendPropertyChanging();
				this._Saldo = value;
				this.SendPropertyChanged("Saldo");
				this.OnSaldoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDomicilio", DbType="Int")]
	public System.Nullable<int> IdDomicilio
	{
		get
		{
			return this._IdDomicilio;
		}
		set
		{
			if ((this._IdDomicilio != value))
			{
				if (this._Domicilio.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdDomicilioChanging(value);
				this.SendPropertyChanging();
				this._IdDomicilio = value;
				this.SendPropertyChanged("IdDomicilio");
				this.OnIdDomicilioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_PedidoVenta", Storage="_PedidoVentas", ThisKey="IdCliente", OtherKey="IdCliente")]
	public EntitySet<PedidoVenta> PedidoVentas
	{
		get
		{
			return this._PedidoVentas;
		}
		set
		{
			this._PedidoVentas.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Domicilio_Cliente", Storage="_Domicilio", ThisKey="IdDomicilio", OtherKey="IdDomicilio", IsForeignKey=true)]
	public Domicilio Domicilio
	{
		get
		{
			return this._Domicilio.Entity;
		}
		set
		{
			Domicilio previousValue = this._Domicilio.Entity;
			if (((previousValue != value) 
						|| (this._Domicilio.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Domicilio.Entity = null;
					previousValue.Clientes.Remove(this);
				}
				this._Domicilio.Entity = value;
				if ((value != null))
				{
					value.Clientes.Add(this);
					this._IdDomicilio = value.IdDomicilio;
				}
				else
				{
					this._IdDomicilio = default(Nullable<int>);
				}
				this.SendPropertyChanged("Domicilio");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_PedidoVentas(PedidoVenta entity)
	{
		this.SendPropertyChanging();
		entity.Cliente = this;
	}
	
	private void detach_PedidoVentas(PedidoVenta entity)
	{
		this.SendPropertyChanging();
		entity.Cliente = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Domicilio")]
public partial class Domicilio : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IdDomicilio;
	
	private string _Calle;
	
	private System.Nullable<int> _Numero;
	
	private string _Localidad;
	
	private System.Nullable<double> _Latitud;
	
	private System.Nullable<double> _Longitud;
	
	private EntitySet<Cliente> _Clientes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDomicilioChanging(int value);
    partial void OnIdDomicilioChanged();
    partial void OnCalleChanging(string value);
    partial void OnCalleChanged();
    partial void OnNumeroChanging(System.Nullable<int> value);
    partial void OnNumeroChanged();
    partial void OnLocalidadChanging(string value);
    partial void OnLocalidadChanged();
    partial void OnLatitudChanging(System.Nullable<double> value);
    partial void OnLatitudChanged();
    partial void OnLongitudChanging(System.Nullable<double> value);
    partial void OnLongitudChanged();
    #endregion
	
	public Domicilio()
	{
		this._Clientes = new EntitySet<Cliente>(new Action<Cliente>(this.attach_Clientes), new Action<Cliente>(this.detach_Clientes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDomicilio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IdDomicilio
	{
		get
		{
			return this._IdDomicilio;
		}
		set
		{
			if ((this._IdDomicilio != value))
			{
				this.OnIdDomicilioChanging(value);
				this.SendPropertyChanging();
				this._IdDomicilio = value;
				this.SendPropertyChanged("IdDomicilio");
				this.OnIdDomicilioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calle", DbType="VarChar(100)")]
	public string Calle
	{
		get
		{
			return this._Calle;
		}
		set
		{
			if ((this._Calle != value))
			{
				this.OnCalleChanging(value);
				this.SendPropertyChanging();
				this._Calle = value;
				this.SendPropertyChanged("Calle");
				this.OnCalleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="Int")]
	public System.Nullable<int> Numero
	{
		get
		{
			return this._Numero;
		}
		set
		{
			if ((this._Numero != value))
			{
				this.OnNumeroChanging(value);
				this.SendPropertyChanging();
				this._Numero = value;
				this.SendPropertyChanged("Numero");
				this.OnNumeroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localidad", DbType="VarChar(100)")]
	public string Localidad
	{
		get
		{
			return this._Localidad;
		}
		set
		{
			if ((this._Localidad != value))
			{
				this.OnLocalidadChanging(value);
				this.SendPropertyChanging();
				this._Localidad = value;
				this.SendPropertyChanged("Localidad");
				this.OnLocalidadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitud", DbType="Float")]
	public System.Nullable<double> Latitud
	{
		get
		{
			return this._Latitud;
		}
		set
		{
			if ((this._Latitud != value))
			{
				this.OnLatitudChanging(value);
				this.SendPropertyChanging();
				this._Latitud = value;
				this.SendPropertyChanged("Latitud");
				this.OnLatitudChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitud", DbType="Float")]
	public System.Nullable<double> Longitud
	{
		get
		{
			return this._Longitud;
		}
		set
		{
			if ((this._Longitud != value))
			{
				this.OnLongitudChanging(value);
				this.SendPropertyChanging();
				this._Longitud = value;
				this.SendPropertyChanged("Longitud");
				this.OnLongitudChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Domicilio_Cliente", Storage="_Clientes", ThisKey="IdDomicilio", OtherKey="IdDomicilio")]
	public EntitySet<Cliente> Clientes
	{
		get
		{
			return this._Clientes;
		}
		set
		{
			this._Clientes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Clientes(Cliente entity)
	{
		this.SendPropertyChanging();
		entity.Domicilio = this;
	}
	
	private void detach_Clientes(Cliente entity)
	{
		this.SendPropertyChanging();
		entity.Domicilio = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PedidoVenta")]
public partial class PedidoVenta : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IdPedidoVenta;
	
	private System.Nullable<bool> _Editable;
	
	private System.Nullable<long> _NroPedido;
	
	private string _Estado;
	
	private System.Nullable<bool> _Entregado;
	
	private System.Nullable<bool> _Pagado;
	
	private System.Nullable<System.DateTime> _FechaPedido;
	
	private System.Nullable<System.DateTime> _FechaEstimadaEntrega;
	
	private System.Nullable<double> _SubTotal;
	
	private System.Nullable<double> _GastosEnvio;
	
	private System.Nullable<double> _MontoTotal;
	
	private System.Nullable<int> _IdCliente;
	
	private System.Nullable<int> _IdVendedor;
	
	private EntitySet<PedidoVentaDetalle> _PedidoVentaDetalles;
	
	private EntityRef<Cliente> _Cliente;
	
	private EntityRef<Vendedor> _Vendedor;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPedidoVentaChanging(int value);
    partial void OnIdPedidoVentaChanged();
    partial void OnEditableChanging(System.Nullable<bool> value);
    partial void OnEditableChanged();
    partial void OnNroPedidoChanging(System.Nullable<long> value);
    partial void OnNroPedidoChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnEntregadoChanging(System.Nullable<bool> value);
    partial void OnEntregadoChanged();
    partial void OnPagadoChanging(System.Nullable<bool> value);
    partial void OnPagadoChanged();
    partial void OnFechaPedidoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaPedidoChanged();
    partial void OnFechaEstimadaEntregaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEstimadaEntregaChanged();
    partial void OnSubTotalChanging(System.Nullable<double> value);
    partial void OnSubTotalChanged();
    partial void OnGastosEnvioChanging(System.Nullable<double> value);
    partial void OnGastosEnvioChanged();
    partial void OnMontoTotalChanging(System.Nullable<double> value);
    partial void OnMontoTotalChanged();
    partial void OnIdClienteChanging(System.Nullable<int> value);
    partial void OnIdClienteChanged();
    partial void OnIdVendedorChanging(System.Nullable<int> value);
    partial void OnIdVendedorChanged();
    #endregion
	
	public PedidoVenta()
	{
		this._PedidoVentaDetalles = new EntitySet<PedidoVentaDetalle>(new Action<PedidoVentaDetalle>(this.attach_PedidoVentaDetalles), new Action<PedidoVentaDetalle>(this.detach_PedidoVentaDetalles));
		this._Cliente = default(EntityRef<Cliente>);
		this._Vendedor = default(EntityRef<Vendedor>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPedidoVenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IdPedidoVenta
	{
		get
		{
			return this._IdPedidoVenta;
		}
		set
		{
			if ((this._IdPedidoVenta != value))
			{
				this.OnIdPedidoVentaChanging(value);
				this.SendPropertyChanging();
				this._IdPedidoVenta = value;
				this.SendPropertyChanged("IdPedidoVenta");
				this.OnIdPedidoVentaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Editable", DbType="Bit")]
	public System.Nullable<bool> Editable
	{
		get
		{
			return this._Editable;
		}
		set
		{
			if ((this._Editable != value))
			{
				this.OnEditableChanging(value);
				this.SendPropertyChanging();
				this._Editable = value;
				this.SendPropertyChanged("Editable");
				this.OnEditableChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NroPedido", DbType="BigInt")]
	public System.Nullable<long> NroPedido
	{
		get
		{
			return this._NroPedido;
		}
		set
		{
			if ((this._NroPedido != value))
			{
				this.OnNroPedidoChanging(value);
				this.SendPropertyChanging();
				this._NroPedido = value;
				this.SendPropertyChanged("NroPedido");
				this.OnNroPedidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this.OnEstadoChanging(value);
				this.SendPropertyChanging();
				this._Estado = value;
				this.SendPropertyChanged("Estado");
				this.OnEstadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Entregado", DbType="Bit")]
	public System.Nullable<bool> Entregado
	{
		get
		{
			return this._Entregado;
		}
		set
		{
			if ((this._Entregado != value))
			{
				this.OnEntregadoChanging(value);
				this.SendPropertyChanging();
				this._Entregado = value;
				this.SendPropertyChanged("Entregado");
				this.OnEntregadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pagado", DbType="Bit")]
	public System.Nullable<bool> Pagado
	{
		get
		{
			return this._Pagado;
		}
		set
		{
			if ((this._Pagado != value))
			{
				this.OnPagadoChanging(value);
				this.SendPropertyChanging();
				this._Pagado = value;
				this.SendPropertyChanged("Pagado");
				this.OnPagadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPedido", DbType="Date")]
	public System.Nullable<System.DateTime> FechaPedido
	{
		get
		{
			return this._FechaPedido;
		}
		set
		{
			if ((this._FechaPedido != value))
			{
				this.OnFechaPedidoChanging(value);
				this.SendPropertyChanging();
				this._FechaPedido = value;
				this.SendPropertyChanged("FechaPedido");
				this.OnFechaPedidoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEstimadaEntrega", DbType="Date")]
	public System.Nullable<System.DateTime> FechaEstimadaEntrega
	{
		get
		{
			return this._FechaEstimadaEntrega;
		}
		set
		{
			if ((this._FechaEstimadaEntrega != value))
			{
				this.OnFechaEstimadaEntregaChanging(value);
				this.SendPropertyChanging();
				this._FechaEstimadaEntrega = value;
				this.SendPropertyChanged("FechaEstimadaEntrega");
				this.OnFechaEstimadaEntregaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="Float")]
	public System.Nullable<double> SubTotal
	{
		get
		{
			return this._SubTotal;
		}
		set
		{
			if ((this._SubTotal != value))
			{
				this.OnSubTotalChanging(value);
				this.SendPropertyChanging();
				this._SubTotal = value;
				this.SendPropertyChanged("SubTotal");
				this.OnSubTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GastosEnvio", DbType="Float")]
	public System.Nullable<double> GastosEnvio
	{
		get
		{
			return this._GastosEnvio;
		}
		set
		{
			if ((this._GastosEnvio != value))
			{
				this.OnGastosEnvioChanging(value);
				this.SendPropertyChanging();
				this._GastosEnvio = value;
				this.SendPropertyChanged("GastosEnvio");
				this.OnGastosEnvioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoTotal", DbType="Float")]
	public System.Nullable<double> MontoTotal
	{
		get
		{
			return this._MontoTotal;
		}
		set
		{
			if ((this._MontoTotal != value))
			{
				this.OnMontoTotalChanging(value);
				this.SendPropertyChanging();
				this._MontoTotal = value;
				this.SendPropertyChanged("MontoTotal");
				this.OnMontoTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int")]
	public System.Nullable<int> IdCliente
	{
		get
		{
			return this._IdCliente;
		}
		set
		{
			if ((this._IdCliente != value))
			{
				if (this._Cliente.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdClienteChanging(value);
				this.SendPropertyChanging();
				this._IdCliente = value;
				this.SendPropertyChanged("IdCliente");
				this.OnIdClienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVendedor", DbType="Int")]
	public System.Nullable<int> IdVendedor
	{
		get
		{
			return this._IdVendedor;
		}
		set
		{
			if ((this._IdVendedor != value))
			{
				if (this._Vendedor.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdVendedorChanging(value);
				this.SendPropertyChanging();
				this._IdVendedor = value;
				this.SendPropertyChanged("IdVendedor");
				this.OnIdVendedorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PedidoVenta_PedidoVentaDetalle", Storage="_PedidoVentaDetalles", ThisKey="IdPedidoVenta", OtherKey="IdPedidoVenta")]
	public EntitySet<PedidoVentaDetalle> PedidoVentaDetalles
	{
		get
		{
			return this._PedidoVentaDetalles;
		}
		set
		{
			this._PedidoVentaDetalles.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_PedidoVenta", Storage="_Cliente", ThisKey="IdCliente", OtherKey="IdCliente", IsForeignKey=true)]
	public Cliente Cliente
	{
		get
		{
			return this._Cliente.Entity;
		}
		set
		{
			Cliente previousValue = this._Cliente.Entity;
			if (((previousValue != value) 
						|| (this._Cliente.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Cliente.Entity = null;
					previousValue.PedidoVentas.Remove(this);
				}
				this._Cliente.Entity = value;
				if ((value != null))
				{
					value.PedidoVentas.Add(this);
					this._IdCliente = value.IdCliente;
				}
				else
				{
					this._IdCliente = default(Nullable<int>);
				}
				this.SendPropertyChanged("Cliente");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vendedor_PedidoVenta", Storage="_Vendedor", ThisKey="IdVendedor", OtherKey="IdVendedor", IsForeignKey=true)]
	public Vendedor Vendedor
	{
		get
		{
			return this._Vendedor.Entity;
		}
		set
		{
			Vendedor previousValue = this._Vendedor.Entity;
			if (((previousValue != value) 
						|| (this._Vendedor.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Vendedor.Entity = null;
					previousValue.PedidoVentas.Remove(this);
				}
				this._Vendedor.Entity = value;
				if ((value != null))
				{
					value.PedidoVentas.Add(this);
					this._IdVendedor = value.IdVendedor;
				}
				else
				{
					this._IdVendedor = default(Nullable<int>);
				}
				this.SendPropertyChanged("Vendedor");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_PedidoVentaDetalles(PedidoVentaDetalle entity)
	{
		this.SendPropertyChanging();
		entity.PedidoVenta = this;
	}
	
	private void detach_PedidoVentaDetalles(PedidoVentaDetalle entity)
	{
		this.SendPropertyChanging();
		entity.PedidoVenta = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PedidoVentaDetalle")]
public partial class PedidoVentaDetalle : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IdPedidoVentaDetalle;
	
	private System.Nullable<int> _Cantidad;
	
	private System.Nullable<double> _SubTotal;
	
	private System.Nullable<double> _PorcentajeDescuento;
	
	private System.Nullable<double> _Total;
	
	private System.Nullable<int> _IdPedidoVenta;
	
	private System.Nullable<int> _IdArticulo;
	
	private EntityRef<Articulo> _Articulo;
	
	private EntityRef<PedidoVenta> _PedidoVenta;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPedidoVentaDetalleChanging(int value);
    partial void OnIdPedidoVentaDetalleChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnSubTotalChanging(System.Nullable<double> value);
    partial void OnSubTotalChanged();
    partial void OnPorcentajeDescuentoChanging(System.Nullable<double> value);
    partial void OnPorcentajeDescuentoChanged();
    partial void OnTotalChanging(System.Nullable<double> value);
    partial void OnTotalChanged();
    partial void OnIdPedidoVentaChanging(System.Nullable<int> value);
    partial void OnIdPedidoVentaChanged();
    partial void OnIdArticuloChanging(System.Nullable<int> value);
    partial void OnIdArticuloChanged();
    #endregion
	
	public PedidoVentaDetalle()
	{
		this._Articulo = default(EntityRef<Articulo>);
		this._PedidoVenta = default(EntityRef<PedidoVenta>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPedidoVentaDetalle", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IdPedidoVentaDetalle
	{
		get
		{
			return this._IdPedidoVentaDetalle;
		}
		set
		{
			if ((this._IdPedidoVentaDetalle != value))
			{
				this.OnIdPedidoVentaDetalleChanging(value);
				this.SendPropertyChanging();
				this._IdPedidoVentaDetalle = value;
				this.SendPropertyChanged("IdPedidoVentaDetalle");
				this.OnIdPedidoVentaDetalleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
	public System.Nullable<int> Cantidad
	{
		get
		{
			return this._Cantidad;
		}
		set
		{
			if ((this._Cantidad != value))
			{
				this.OnCantidadChanging(value);
				this.SendPropertyChanging();
				this._Cantidad = value;
				this.SendPropertyChanged("Cantidad");
				this.OnCantidadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubTotal", DbType="Float")]
	public System.Nullable<double> SubTotal
	{
		get
		{
			return this._SubTotal;
		}
		set
		{
			if ((this._SubTotal != value))
			{
				this.OnSubTotalChanging(value);
				this.SendPropertyChanging();
				this._SubTotal = value;
				this.SendPropertyChanged("SubTotal");
				this.OnSubTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcentajeDescuento", DbType="Float")]
	public System.Nullable<double> PorcentajeDescuento
	{
		get
		{
			return this._PorcentajeDescuento;
		}
		set
		{
			if ((this._PorcentajeDescuento != value))
			{
				this.OnPorcentajeDescuentoChanging(value);
				this.SendPropertyChanging();
				this._PorcentajeDescuento = value;
				this.SendPropertyChanged("PorcentajeDescuento");
				this.OnPorcentajeDescuentoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Float")]
	public System.Nullable<double> Total
	{
		get
		{
			return this._Total;
		}
		set
		{
			if ((this._Total != value))
			{
				this.OnTotalChanging(value);
				this.SendPropertyChanging();
				this._Total = value;
				this.SendPropertyChanged("Total");
				this.OnTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPedidoVenta", DbType="Int")]
	public System.Nullable<int> IdPedidoVenta
	{
		get
		{
			return this._IdPedidoVenta;
		}
		set
		{
			if ((this._IdPedidoVenta != value))
			{
				if (this._PedidoVenta.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdPedidoVentaChanging(value);
				this.SendPropertyChanging();
				this._IdPedidoVenta = value;
				this.SendPropertyChanged("IdPedidoVenta");
				this.OnIdPedidoVentaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArticulo", DbType="Int")]
	public System.Nullable<int> IdArticulo
	{
		get
		{
			return this._IdArticulo;
		}
		set
		{
			if ((this._IdArticulo != value))
			{
				if (this._Articulo.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdArticuloChanging(value);
				this.SendPropertyChanging();
				this._IdArticulo = value;
				this.SendPropertyChanged("IdArticulo");
				this.OnIdArticuloChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Articulo_PedidoVentaDetalle", Storage="_Articulo", ThisKey="IdArticulo", OtherKey="IdArticulo", IsForeignKey=true)]
	public Articulo Articulo
	{
		get
		{
			return this._Articulo.Entity;
		}
		set
		{
			Articulo previousValue = this._Articulo.Entity;
			if (((previousValue != value) 
						|| (this._Articulo.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Articulo.Entity = null;
					previousValue.PedidoVentaDetalles.Remove(this);
				}
				this._Articulo.Entity = value;
				if ((value != null))
				{
					value.PedidoVentaDetalles.Add(this);
					this._IdArticulo = value.IdArticulo;
				}
				else
				{
					this._IdArticulo = default(Nullable<int>);
				}
				this.SendPropertyChanged("Articulo");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PedidoVenta_PedidoVentaDetalle", Storage="_PedidoVenta", ThisKey="IdPedidoVenta", OtherKey="IdPedidoVenta", IsForeignKey=true)]
	public PedidoVenta PedidoVenta
	{
		get
		{
			return this._PedidoVenta.Entity;
		}
		set
		{
			PedidoVenta previousValue = this._PedidoVenta.Entity;
			if (((previousValue != value) 
						|| (this._PedidoVenta.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._PedidoVenta.Entity = null;
					previousValue.PedidoVentaDetalles.Remove(this);
				}
				this._PedidoVenta.Entity = value;
				if ((value != null))
				{
					value.PedidoVentaDetalles.Add(this);
					this._IdPedidoVenta = value.IdPedidoVenta;
				}
				else
				{
					this._IdPedidoVenta = default(Nullable<int>);
				}
				this.SendPropertyChanged("PedidoVenta");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rubro")]
public partial class Rubro : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IdRubro;
	
	private string _Codigo;
	
	private string _Denominacion;
	
	private System.Nullable<int> _IdRubroSuperior;
	
	private EntitySet<Articulo> _Articulos;
	
	private EntitySet<Rubro> _Rubros;
	
	private EntityRef<Rubro> _Rubro1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRubroChanging(int value);
    partial void OnIdRubroChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnDenominacionChanging(string value);
    partial void OnDenominacionChanged();
    partial void OnIdRubroSuperiorChanging(System.Nullable<int> value);
    partial void OnIdRubroSuperiorChanged();
    #endregion
	
	public Rubro()
	{
		this._Articulos = new EntitySet<Articulo>(new Action<Articulo>(this.attach_Articulos), new Action<Articulo>(this.detach_Articulos));
		this._Rubros = new EntitySet<Rubro>(new Action<Rubro>(this.attach_Rubros), new Action<Rubro>(this.detach_Rubros));
		this._Rubro1 = default(EntityRef<Rubro>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRubro", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IdRubro
	{
		get
		{
			return this._IdRubro;
		}
		set
		{
			if ((this._IdRubro != value))
			{
				this.OnIdRubroChanging(value);
				this.SendPropertyChanging();
				this._IdRubro = value;
				this.SendPropertyChanged("IdRubro");
				this.OnIdRubroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="VarChar(20)")]
	public string Codigo
	{
		get
		{
			return this._Codigo;
		}
		set
		{
			if ((this._Codigo != value))
			{
				this.OnCodigoChanging(value);
				this.SendPropertyChanging();
				this._Codigo = value;
				this.SendPropertyChanged("Codigo");
				this.OnCodigoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Denominacion", DbType="VarChar(200)")]
	public string Denominacion
	{
		get
		{
			return this._Denominacion;
		}
		set
		{
			if ((this._Denominacion != value))
			{
				this.OnDenominacionChanging(value);
				this.SendPropertyChanging();
				this._Denominacion = value;
				this.SendPropertyChanged("Denominacion");
				this.OnDenominacionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRubroSuperior", DbType="Int")]
	public System.Nullable<int> IdRubroSuperior
	{
		get
		{
			return this._IdRubroSuperior;
		}
		set
		{
			if ((this._IdRubroSuperior != value))
			{
				if (this._Rubro1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIdRubroSuperiorChanging(value);
				this.SendPropertyChanging();
				this._IdRubroSuperior = value;
				this.SendPropertyChanged("IdRubroSuperior");
				this.OnIdRubroSuperiorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rubro_Articulo", Storage="_Articulos", ThisKey="IdRubro", OtherKey="IdRubro")]
	public EntitySet<Articulo> Articulos
	{
		get
		{
			return this._Articulos;
		}
		set
		{
			this._Articulos.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rubro_Rubro", Storage="_Rubros", ThisKey="IdRubro", OtherKey="IdRubroSuperior")]
	public EntitySet<Rubro> Rubros
	{
		get
		{
			return this._Rubros;
		}
		set
		{
			this._Rubros.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Rubro_Rubro", Storage="_Rubro1", ThisKey="IdRubroSuperior", OtherKey="IdRubro", IsForeignKey=true)]
	public Rubro Rubro1
	{
		get
		{
			return this._Rubro1.Entity;
		}
		set
		{
			Rubro previousValue = this._Rubro1.Entity;
			if (((previousValue != value) 
						|| (this._Rubro1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Rubro1.Entity = null;
					previousValue.Rubros.Remove(this);
				}
				this._Rubro1.Entity = value;
				if ((value != null))
				{
					value.Rubros.Add(this);
					this._IdRubroSuperior = value.IdRubro;
				}
				else
				{
					this._IdRubroSuperior = default(Nullable<int>);
				}
				this.SendPropertyChanged("Rubro1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Articulos(Articulo entity)
	{
		this.SendPropertyChanging();
		entity.Rubro = this;
	}
	
	private void detach_Articulos(Articulo entity)
	{
		this.SendPropertyChanging();
		entity.Rubro = null;
	}
	
	private void attach_Rubros(Rubro entity)
	{
		this.SendPropertyChanging();
		entity.Rubro1 = this;
	}
	
	private void detach_Rubros(Rubro entity)
	{
		this.SendPropertyChanging();
		entity.Rubro1 = null;
	}
}
#pragma warning restore 1591
